### ISSUE TITLE
Bug : Block and BoundingBox

### ISSUE THREAD

**Issue by AxelRinghausen** [Dessia-tech/volmdlr#1105]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **What is the current behavior?**
Taking this BoundingBox, converting it to a Block using Block.from_bounding_box, and taking the BoundingBox of this Block result in two different BoundingBox. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages
```
import volmdlr.core
import volmdlr.primitives3d
bbox1 = volmdlr.core.BoundingBox(-0.0271021, 1.0271020999999998, -0.4024024, 0.8024024000000001, -0.0261011, 0.5261011000000001)
block = volmdlr.primitives3d.Block.from_bounding_box(bbox1)
bbox2 = block.bounding_box
print(bbox1 == bbox2)
```

* **What is the expected behavior?**
I expect this code to print True

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: dev
  - commit: 564e71bb9fba4cab5c2d04c7594e3dd805ab65df
  - python version: 3.8

**Comment by pgibertini** [comment]
Unfortunately, bounding_box created this way can't be perfectly equal due to floating point arithmetic.
However, I created a specific `Block.get_bounding_box` method because the actual one was imprecise. 
Moreover, I implemented a `BoundingBox.is_close` method to see if two bounding boxes are equal at a given tolerance, and bypass the floating point arithmetic imprecision.
